name: CD Workflow

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  ci-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Build and test
        run: |
          docker compose up --build -d
          sleep 15
          docker compose ps
          # Ajouter vos tests ici
          docker compose down

  deploy:
    needs: ci-steps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            elhadido/my-app:latest
            elhadido/my-app:${{ github.sha }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('elhadido/my-app:{0}', github.ref_name) || '' }}

      - name: Generate Release Notes
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: "Release ${{ github.ref_name }}"
          token: ${{ secrets.TOKEN }}
