name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      !startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push latest Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            elhadido/my-app:latest

  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push versioned Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            elhadido/my-app:${{ github.ref_name }}

      - name: Generate Release Notes
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: "Release ${{ github.ref_name }}"
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }}
