name: CD Test Workflow

on:
  push:
    branches:
      - main
      - feature/cd
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            elhadido/my-app:latest
            elhadido/my-app:${{ github.sha }}
          cache-from: type=registry,ref=elhadido/my-app:latest
          cache-to: type=inline
