name: CI Workflow

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Build and run Docker containers
        run: |
          docker compose up --build -d
          sleep 15  # Attendre que MySQL démarre avant d'afficher les logs

      - name: Check MySQL logs
        if: always()
        run: docker logs projet_ci_cd-db-1
      
      - name: Vérifier les conteneurs en cours d'exécution
        if: always()
        run: docker ps -a

      - name: Run test
        run: docker compose exec app npm test

      - name: Stop Docker containers
        if: always()
        run: docker compose down
