name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest tag
        id: latest-tag
        run: echo "TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")" >> $GITHUB_ENV

      - name: Calculate next version
        id: version
        run: |
          LATEST_TAG=${TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG:-0.0.0}"
          NEW_VERSION="v$MAJOR.$MINOR.$((PATCH+1))"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
